package jetbrains.mps.samples.KajaAndOr;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.TemplateModuleBase;
import jetbrains.mps.smodel.language.LanguageRuntime;
import java.util.Collection;
import jetbrains.mps.generator.runtime.TemplateMappingPriorityRule;
import jetbrains.mps.generator.runtime.TemplateModel;
import jetbrains.mps.smodel.language.LanguageRegistry;
import jetbrains.mps.generator.runtime.TemplateUtil;
import jetbrains.mps.samples.KajaAndOr.generator.template.main.TemplateModelImpl;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.module.SModuleReference;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import org.jetbrains.mps.openapi.language.SLanguage;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Generator extends TemplateModuleBase {
  private final LanguageRuntime sourceLanguage;
  private final Collection<TemplateMappingPriorityRule> priorities;
  private TemplateModel[] models;

  public Generator(LanguageRegistry languageRegistry, LanguageRuntime sourceLanguage) {
    super(languageRegistry);
    this.sourceLanguage = sourceLanguage;
    priorities = TemplateUtil.asCollection(TemplateUtil.createStrictlyTogetherRule(TemplateUtil.createRefExternal("2b337a26-63f3-47f2-840c-26f48eebe5fa(jetbrains.mps.samples.KajaAndOr#1904811872814327543)", TemplateUtil.createRefLocal()), TemplateUtil.createRefExternal("e104ec4c-a001-4f8f-b6bf-654f6a062891(jetbrains.mps.samples.Kaja#3265739055509559144)", TemplateUtil.createRefLocal())));
  }
  @Override
  public String getAlias() {
    return "jetbrains.mps.samples.KajaAndOr/<no name>";
  }

  @Override
  public Collection<TemplateModel> getModels() {
    if (models == null) {
      models = new TemplateModel[1];
      models[0] = new TemplateModelImpl(this);
    }
    return Arrays.asList(models);
  }

  @Override
  public Collection<TemplateMappingPriorityRule> getPriorities() {
    return priorities;
  }

  @NotNull
  @Override
  public SModuleReference getModuleReference() {
    return PersistenceFacade.getInstance().createModuleReference("2b337a26-63f3-47f2-840c-26f48eebe5fa(jetbrains.mps.samples.KajaAndOr#1904811872814327543)");
  }

  @Override
  public Collection<SLanguage> getTargetLanguages() {
    SLanguage[] rv = new SLanguage[1];
    rv[0] = MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage");
    return Arrays.asList(rv);
  }

  @Override
  @NotNull
  public LanguageRuntime getSourceLanguage() {
    return sourceLanguage;
  }

  @Override
  protected void fillReferencedGenerators(TemplateModuleBase.ReferencedGenerators referencedGenerators) {
    referencedGenerators.employed("e104ec4c-a001-4f8f-b6bf-654f6a062891(jetbrains.mps.samples.Kaja#3265739055509559144)");
  }
}
