package jetbrains.mps.samples.KajaSceneConstruction.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum orientation {
  horizontal("horizontal", "horizontal"),
  vertical("vertical", "vertical");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private orientation(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<orientation> getConstants() {
    List<orientation> list = ListSequence.fromList(new LinkedList<orientation>());
    ListSequence.fromList(list).addElement(orientation.horizontal);
    ListSequence.fromList(list).addElement(orientation.vertical);
    return list;
  }
  public static orientation getDefault() {
    return null;
  }
  public static orientation parseValue(String value) {
    if (value == null) {
      return orientation.getDefault();
    }
    if (value.equals(orientation.horizontal.getValueAsString())) {
      return orientation.horizontal;
    }
    if (value.equals(orientation.vertical.getValueAsString())) {
      return orientation.vertical;
    }
    return orientation.getDefault();
  }
}
