package jetbrains.mps.samples.KajaSceneConstruction.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.runtime.TemplateDeclarationBase;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.generator.runtime.TemplateContext;
import jetbrains.mps.generator.runtime.GenerationException;
import jetbrains.mps.generator.runtime.TemplateExecutionEnvironment;
import org.jetbrains.mps.openapi.model.SNodeAccessUtil;
import jetbrains.mps.smodel.SReference;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import jetbrains.mps.generator.runtime.TemplateUtil;
import jetbrains.mps.generator.template.PropertyMacroContext;
import java.util.Collection;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import jetbrains.mps.generator.runtime.NodeWeaveFacility;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SConcept;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SContainmentLink;

@Generated
public class Template_reduce_Vehicle extends TemplateDeclarationBase {

  public Template_reduce_Vehicle() {
  }

  public SNodeReference getTemplateNode() {
    return new SNodePointer("r:262b93f0-fe86-497c-93c5-efd684d05bc6(jetbrains.mps.samples.KajaSceneConstruction.generator.template.main@generator)", "6504511466433158332");
  }
  protected SNode applyPart0(@NotNull final TemplateContext context) throws GenerationException {
    final TemplateExecutionEnvironment environment = context.getEnvironment();
    final SNode tnode1 = environment.createOutputNode(myConcepts[0]);
    try {
      TemplateContext context1 = context.subContext();
      {
        final SNode tnode2 = environment.createOutputNode(myConcepts[1]);
        try {
          TemplateContext context2 = context1.subContext();
          {
            final SNode tnode3 = environment.createOutputNode(myConcepts[2]);
            try {
              TemplateContext context3 = context2.subContext();
              {
                final SNode tnode4 = environment.createOutputNode(myConcepts[3]);
                try {
                  SNodeAccessUtil.setProperty(tnode4, myProperties[0], "check if starting position is allowed.");
                } finally {
                }
                tnode3.addChild(myAggregationLinks[0], tnode4);
                // TODO validate child 
              }
            } finally {
            }
            tnode2.addChild(myAggregationLinks[1], tnode3);
            // TODO validate child 
          }
          {
            final SNode tnode5 = environment.createOutputNode(myConcepts[2]);
            try {
              TemplateContext context4 = context2.subContext();
              {
                final SNode tnode6 = environment.createOutputNode(myConcepts[3]);
                try {
                  SNodeAccessUtil.setProperty(tnode6, myProperties[0], "check if destination position is allowed.");
                } finally {
                }
                tnode5.addChild(myAggregationLinks[0], tnode6);
                // TODO validate child 
              }
            } finally {
            }
            tnode2.addChild(myAggregationLinks[1], tnode5);
            // TODO validate child 
          }
          {
            final SNode tnode7 = environment.createOutputNode(myConcepts[2]);
            try {
              TemplateContext context5 = context2.subContext();
              {
                final SNode tnode8 = environment.createOutputNode(myConcepts[3]);
                try {
                  SNodeAccessUtil.setProperty(tnode8, myProperties[0], "if so, then create vehicle and add vehicle to cell at starting position");
                } finally {
                }
                tnode7.addChild(myAggregationLinks[0], tnode8);
                // TODO validate child 
              }
            } finally {
            }
            tnode2.addChild(myAggregationLinks[1], tnode7);
            // TODO validate child 
          }
          {
            final SNode tnode9 = environment.createOutputNode(myConcepts[4]);
            try {
              TemplateContext context6 = context2.subContext();
              {
                final SNode tnode10 = environment.createOutputNode(myConcepts[1]);
                try {
                  TemplateContext context7 = context6.subContext();
                  {
                    final SNode tnode11 = environment.createOutputNode(myConcepts[2]);
                    try {
                      TemplateContext context8 = context7.subContext();
                      {
                        final SNode tnode12 = environment.createOutputNode(myConcepts[3]);
                        try {
                          SNodeAccessUtil.setProperty(tnode12, myProperties[0], "check if vehicle is drivable here");
                        } finally {
                        }
                        tnode11.addChild(myAggregationLinks[0], tnode12);
                        // TODO validate child 
                      }
                    } finally {
                    }
                    tnode10.addChild(myAggregationLinks[1], tnode11);
                    // TODO validate child 
                  }
                  {
                    final SNode tnode13 = environment.createOutputNode(myConcepts[4]);
                    try {
                      TemplateContext context9 = context7.subContext();
                      {
                        final SNode tnode14 = environment.createOutputNode(myConcepts[1]);
                        try {
                          TemplateContext context10 = context9.subContext();
                          {
                            final SNode tnode15 = environment.createOutputNode(myConcepts[2]);
                            try {
                              TemplateContext context11 = context10.subContext();
                              {
                                final SNode tnode16 = environment.createOutputNode(myConcepts[3]);
                                try {
                                  SNodeAccessUtil.setProperty(tnode16, myProperties[0], "create a new vehicle");
                                } finally {
                                }
                                tnode15.addChild(myAggregationLinks[0], tnode16);
                                // TODO validate child 
                              }
                            } finally {
                            }
                            tnode14.addChild(myAggregationLinks[1], tnode15);
                            // TODO validate child 
                          }
                          {
                            final SNode tnode17 = environment.createOutputNode(myConcepts[5]);
                            try {
                              TemplateContext context12 = context10.subContext();
                              {
                                final SNode tnode18 = environment.createOutputNode(myConcepts[6]);
                                try {
                                  environment.nodeCopied(context12, tnode18, "tpl/r:262b93f0-fe86-497c-93c5-efd684d05bc6/6504511466437641999");
                                  SNodeAccessUtil.setProperty(tnode18, myProperties[1], "vehicle");
                                  TemplateContext context13 = context12.subContext();
                                  {
                                    final SNode tnode19 = environment.createOutputNode(myConcepts[7]);
                                    try {
                                      tnode19.setReference(myAssociationLinks[0], SReference.create(myAssociationLinks[0], tnode19, PersistenceFacade.getInstance().createModelReference("r:f5e9b11f-5073-4786-8ed1-a9e42307c3f8(JavaKaja.runtime)"), PersistenceFacade.getInstance().createNodeId("2000624636386186018")));
                                    } finally {
                                    }
                                    tnode18.addChild(myAggregationLinks[2], tnode19);
                                    // TODO validate child 
                                  }
                                  {
                                    final SNode tnode20 = environment.createOutputNode(myConcepts[8]);
                                    try {
                                      TemplateContext context14 = context13.subContext();
                                      {
                                        final SNode tnode21 = environment.createOutputNode(myConcepts[9]);
                                        try {
                                          tnode21.setReference(myAssociationLinks[1], SReference.create(myAssociationLinks[1], tnode21, PersistenceFacade.getInstance().createModelReference("r:f5e9b11f-5073-4786-8ed1-a9e42307c3f8(JavaKaja.runtime)"), PersistenceFacade.getInstance().createNodeId("2000624636392834663")));
                                          TemplateContext context15 = context14.subContext();
                                          {
                                            final SNode tnode22 = environment.createOutputNode(myConcepts[8]);
                                            try {
                                              TemplateContext context16 = context15.subContext();
                                              {
                                                final SNode tnode23 = environment.createOutputNode(myConcepts[9]);
                                                try {
                                                  tnode23.setReference(myAssociationLinks[1], SReference.create(myAssociationLinks[1], tnode23, PersistenceFacade.getInstance().createModelReference("r:f5e9b11f-5073-4786-8ed1-a9e42307c3f8(JavaKaja.runtime)"), PersistenceFacade.getInstance().createNodeId("1293158935850904729")));
                                                  TemplateContext context17 = context16.subContext();
                                                  {
                                                    final SNode tnode24 = environment.createOutputNode(myConcepts[10]);
                                                    try {
                                                      SNodeAccessUtil.setProperty(tnode24, myProperties[2], TemplateUtil.asString(QueriesGenerated.propertyMacro_GetPropertyValue_6504511466437722203(new PropertyMacroContext(context17, "0", propertyMacro_yon54s_c0a0c0a0b0c0b0b0b0c0b0b0b0e0b0b0b0c0b0b0b0c0b0b0b0e0b0b0c0e))));
                                                    } finally {
                                                    }
                                                    tnode23.addChild(myAggregationLinks[3], tnode24);
                                                    // TODO validate child 
                                                  }
                                                  {
                                                    final SNode tnode25 = environment.createOutputNode(myConcepts[10]);
                                                    try {
                                                      SNodeAccessUtil.setProperty(tnode25, myProperties[2], TemplateUtil.asString(QueriesGenerated.propertyMacro_GetPropertyValue_6504511466437729264(new PropertyMacroContext(context17, "0", propertyMacro_yon54s_c0a0c0a0b0d0b0b0b0c0b0b0b0e0b0b0b0c0b0b0b0c0b0b0b0e0b0b0c0e))));
                                                    } finally {
                                                    }
                                                    tnode23.addChild(myAggregationLinks[3], tnode25);
                                                    // TODO validate child 
                                                  }
                                                } finally {
                                                }
                                                tnode22.addChild(myAggregationLinks[4], tnode23);
                                                // TODO validate child 
                                              }
                                            } finally {
                                            }
                                            tnode21.addChild(myAggregationLinks[3], tnode22);
                                            // TODO validate child 
                                          }
                                          {
                                            final SNode tnode26 = environment.createOutputNode(myConcepts[8]);
                                            try {
                                              TemplateContext context18 = context15.subContext();
                                              {
                                                final SNode tnode27 = environment.createOutputNode(myConcepts[9]);
                                                try {
                                                  tnode27.setReference(myAssociationLinks[1], SReference.create(myAssociationLinks[1], tnode27, PersistenceFacade.getInstance().createModelReference("r:f5e9b11f-5073-4786-8ed1-a9e42307c3f8(JavaKaja.runtime)"), PersistenceFacade.getInstance().createNodeId("1293158935850904729")));
                                                  TemplateContext context19 = context18.subContext();
                                                  {
                                                    final SNode tnode28 = environment.createOutputNode(myConcepts[10]);
                                                    try {
                                                      SNodeAccessUtil.setProperty(tnode28, myProperties[2], TemplateUtil.asString(QueriesGenerated.propertyMacro_GetPropertyValue_6504511466437736826(new PropertyMacroContext(context19, "1", propertyMacro_yon54s_c0a0c0a0b0c0b0b0b0d0b0b0b0e0b0b0b0c0b0b0b0c0b0b0b0e0b0b0c0e))));
                                                    } finally {
                                                    }
                                                    tnode27.addChild(myAggregationLinks[3], tnode28);
                                                    // TODO validate child 
                                                  }
                                                  {
                                                    final SNode tnode29 = environment.createOutputNode(myConcepts[10]);
                                                    try {
                                                      SNodeAccessUtil.setProperty(tnode29, myProperties[2], TemplateUtil.asString(QueriesGenerated.propertyMacro_GetPropertyValue_6504511466437743197(new PropertyMacroContext(context19, "1", propertyMacro_yon54s_c0a0c0a0b0d0b0b0b0d0b0b0b0e0b0b0b0c0b0b0b0c0b0b0b0e0b0b0c0e))));
                                                    } finally {
                                                    }
                                                    tnode27.addChild(myAggregationLinks[3], tnode29);
                                                    // TODO validate child 
                                                  }
                                                } finally {
                                                }
                                                tnode26.addChild(myAggregationLinks[4], tnode27);
                                                // TODO validate child 
                                              }
                                            } finally {
                                            }
                                            tnode21.addChild(myAggregationLinks[3], tnode26);
                                            // TODO validate child 
                                          }
                                          {
                                            Collection<SNode> tlist30 = null;
                                            final SNode copySrcInput30 = QueriesGenerated.sourceNodeQuery_2286872346382915221(new SourceSubstituteMacroNodeContext(context15, copySrcMacro_yon54s_b0a0c0e0b0b0b0e0b0b0b0c0b0b0b0c0b0b0b0e0b0b0c0e));
                                            tlist30 = environment.copyNodes(TemplateUtil.singletonList(copySrcInput30), copySrcMacro_yon54s_b0a0c0e0b0b0b0e0b0b0b0c0b0b0b0c0b0b0b0e0b0b0c0e, "tpl/r:262b93f0-fe86-497c-93c5-efd684d05bc6/2286872346382913299", context15);
                                            for (SNode child31 : TemplateUtil.asNotNull(tlist30)) {
                                              tnode21.addChild(myAggregationLinks[3], child31);
                                            }
                                            // TODO validate child 
                                          }
                                          {
                                            Collection<SNode> tlist32 = null;
                                            try {
                                              TemplateContext switchContext32;
                                              switchContext32 = context15;
                                              tlist32 = environment.trySwitch(templateSwitchNodeNoInput_yon54s_a0a0c0b0f0b0b0b0e0b0b0b0c0b0b0b0c0b0b0b0e0b0b0c0e, switchContext32);
                                              if (tlist32 == null) {
                                                Collection<SNode> tlist33 = null;
                                                final Iterable<SNode> copyListInput33 = QueriesGenerated.sourceNodesQuery_6504511466447542751(new SourceSubstituteMacroNodesContext(context15, copySrcListMacro_yon54s_b0a0a1a3a1a5a1a1a1a4a1a1a1a2a1a1a1a2a1a1a1a4a1a1a2a4));
                                                tlist33 = environment.copyNodes(copyListInput33, copySrcListMacro_yon54s_b0a0a1a3a1a5a1a1a1a4a1a1a1a2a1a1a1a2a1a1a1a4a1a1a2a4, "tpl/r:262b93f0-fe86-497c-93c5-efd684d05bc6/6504511466447012864", context15);
                                                if (tlist33 != null) {
                                                  tlist32 = tlist33;
                                                }
                                              }
                                            } finally {
                                            }
                                            for (SNode child34 : TemplateUtil.asNotNull(tlist32)) {
                                              tnode21.addChild(myAggregationLinks[3], child34);
                                            }
                                            // TODO validate child 
                                          }
                                        } finally {
                                        }
                                        tnode20.addChild(myAggregationLinks[4], tnode21);
                                        // TODO validate child 
                                      }
                                    } finally {
                                    }
                                    tnode18.addChild(myAggregationLinks[5], tnode20);
                                    // TODO validate child 
                                  }
                                } finally {
                                }
                                tnode17.addChild(myAggregationLinks[6], tnode18);
                                // TODO validate child 
                              }
                            } finally {
                            }
                            tnode14.addChild(myAggregationLinks[1], tnode17);
                            // TODO validate child 
                          }
                          {
                            final SNode tnode35 = environment.createOutputNode(myConcepts[11]);
                            try {
                            } finally {
                            }
                            tnode14.addChild(myAggregationLinks[1], tnode35);
                            // TODO validate child 
                          }
                          {
                            final SNode tnode36 = environment.createOutputNode(myConcepts[12]);
                            try {
                              TemplateContext context20 = context10.subContext();
                              {
                                final SNode tnode37 = environment.createOutputNode(myConcepts[13]);
                                try {
                                  tnode37.setReference(myAssociationLinks[1], SReference.create(myAssociationLinks[1], tnode37, PersistenceFacade.getInstance().createModelReference("r:f5e9b11f-5073-4786-8ed1-a9e42307c3f8(JavaKaja.runtime)"), PersistenceFacade.getInstance().createNodeId("6504511466438260656")));
                                  TemplateContext context21 = context20.subContext();
                                  {
                                    final SNode tnode38 = environment.createOutputNode(myConcepts[10]);
                                    try {
                                      SNodeAccessUtil.setProperty(tnode38, myProperties[2], TemplateUtil.asString(QueriesGenerated.propertyMacro_GetPropertyValue_6504511466439200434(new PropertyMacroContext(context21, "0", propertyMacro_yon54s_c0a0c0a0b0c0b0b0b0e0b0b0b0c0b0b0b0e0b0b0c0e))));
                                    } finally {
                                    }
                                    tnode37.addChild(myAggregationLinks[3], tnode38);
                                    // TODO validate child 
                                  }
                                  {
                                    final SNode tnode39 = environment.createOutputNode(myConcepts[10]);
                                    try {
                                      SNodeAccessUtil.setProperty(tnode39, myProperties[2], TemplateUtil.asString(QueriesGenerated.propertyMacro_GetPropertyValue_6504511466439208105(new PropertyMacroContext(context21, "0", propertyMacro_yon54s_c0a0c0a0b0d0b0b0b0e0b0b0b0c0b0b0b0e0b0b0c0e))));
                                    } finally {
                                    }
                                    tnode37.addChild(myAggregationLinks[3], tnode39);
                                    // TODO validate child 
                                  }
                                  {
                                    final SNode tnode40 = environment.createOutputNode(myConcepts[14]);
                                    try {
                                      environment.resolveInTemplateLater(tnode40, myAssociationLinks[2], templateNode_yon54s_c0a0a1a4a1a1a1a4a1a1a1a2a1a1a1a4a1a1a2a4, "tpl/r:262b93f0-fe86-497c-93c5-efd684d05bc6/6504511466437641999", "vehicle", context21);
                                    } finally {
                                    }
                                    tnode37.addChild(myAggregationLinks[3], tnode40);
                                    // TODO validate child 
                                  }
                                } finally {
                                }
                                tnode36.addChild(myAggregationLinks[7], tnode37);
                                // TODO validate child 
                              }
                            } finally {
                            }
                            tnode14.addChild(myAggregationLinks[1], tnode36);
                            // TODO validate child 
                          }
                          {
                            final SNode tnode41 = environment.createOutputNode(myConcepts[2]);
                            try {
                              TemplateContext context22 = context10.subContext();
                              {
                                final SNode tnode42 = environment.createOutputNode(myConcepts[3]);
                                try {
                                  SNodeAccessUtil.setProperty(tnode42, myProperties[0], "place vehcile in this starting position");
                                } finally {
                                }
                                tnode41.addChild(myAggregationLinks[0], tnode42);
                                // TODO validate child 
                              }
                            } finally {
                            }
                            tnode14.addChild(myAggregationLinks[1], tnode41);
                            // TODO validate child 
                          }
                          {
                            final SNode tnode43 = environment.createOutputNode(myConcepts[11]);
                            try {
                            } finally {
                            }
                            tnode14.addChild(myAggregationLinks[1], tnode43);
                            // TODO validate child 
                          }
                        } finally {
                        }
                        tnode13.addChild(myAggregationLinks[8], tnode14);
                        // TODO validate child 
                      }
                      {
                        final SNode tnode44 = environment.createOutputNode(myConcepts[15]);
                        try {
                          TemplateContext context23 = context9.subContext();
                          {
                            final SNode tnode45 = environment.createOutputNode(myConcepts[16]);
                            try {
                              TemplateContext context24 = context23.subContext();
                              {
                                final SNode tnode46 = environment.createOutputNode(myConcepts[10]);
                                try {
                                  SNodeAccessUtil.setProperty(tnode46, myProperties[2], TemplateUtil.asString(QueriesGenerated.propertyMacro_GetPropertyValue_6504511466437709893(new PropertyMacroContext(context24, "0", propertyMacro_yon54s_c0a0c0a0b0b0b0b0b0c0b0c0b0b0b0e0b0b0c0e))));
                                } finally {
                                }
                                tnode45.addChild(myAggregationLinks[9], tnode46);
                                // TODO validate child 
                              }
                              {
                                final SNode tnode47 = environment.createOutputNode(myConcepts[16]);
                                try {
                                  TemplateContext context25 = context24.subContext();
                                  {
                                    final SNode tnode48 = environment.createOutputNode(myConcepts[10]);
                                    try {
                                      SNodeAccessUtil.setProperty(tnode48, myProperties[2], TemplateUtil.asString(QueriesGenerated.propertyMacro_GetPropertyValue_6504511466437702718(new PropertyMacroContext(context25, "0", propertyMacro_yon54s_c0a0c0a0b0b0b0c0b0b0b0c0b0c0b0b0b0e0b0b0c0e))));
                                    } finally {
                                    }
                                    tnode47.addChild(myAggregationLinks[9], tnode48);
                                    // TODO validate child 
                                  }
                                  {
                                    final SNode tnode49 = environment.createOutputNode(myConcepts[14]);
                                    try {
                                      tnode49.setReference(myAssociationLinks[2], SReference.create(myAssociationLinks[2], tnode49, PersistenceFacade.getInstance().createModelReference("r:f5e9b11f-5073-4786-8ed1-a9e42307c3f8(JavaKaja.runtime)"), PersistenceFacade.getInstance().createNodeId("3308300503039569315")));
                                    } finally {
                                    }
                                    tnode47.addChild(myAggregationLinks[10], tnode49);
                                    // TODO validate child 
                                  }
                                } finally {
                                }
                                tnode45.addChild(myAggregationLinks[10], tnode47);
                                // TODO validate child 
                              }
                            } finally {
                            }
                            tnode44.addChild(myAggregationLinks[11], tnode45);
                            // TODO validate child 
                          }
                          {
                            final SNode tnode50 = environment.createOutputNode(myConcepts[17]);
                            try {
                              tnode50.setReference(myAssociationLinks[1], SReference.create(myAssociationLinks[1], tnode50, PersistenceFacade.getInstance().createModelReference("r:f5e9b11f-5073-4786-8ed1-a9e42307c3f8(JavaKaja.runtime)"), PersistenceFacade.getInstance().createNodeId("2000624636386249075")));
                              TemplateContext context26 = context23.subContext();
                              {
                                Collection<SNode> tlist51 = null;
                                final SNode copySrcInput51 = QueriesGenerated.sourceNodeQuery_2286872346383052770(new SourceSubstituteMacroNodeContext(context26, copySrcMacro_yon54s_b0a0c0c0b0c0b0c0b0c0b0b0b0e0b0b0c0e));
                                tlist51 = environment.copyNodes(TemplateUtil.singletonList(copySrcInput51), copySrcMacro_yon54s_b0a0c0c0b0c0b0c0b0c0b0b0b0e0b0b0c0e, "tpl/r:262b93f0-fe86-497c-93c5-efd684d05bc6/2286872346383047509", context26);
                                for (SNode child52 : TemplateUtil.asNotNull(tlist51)) {
                                  tnode50.addChild(myAggregationLinks[3], child52);
                                }
                                // TODO validate child 
                              }
                            } finally {
                            }
                            tnode44.addChild(myAggregationLinks[12], tnode50);
                            // TODO validate child 
                          }
                        } finally {
                        }
                        tnode13.addChild(myAggregationLinks[13], tnode44);
                        // TODO validate child 
                      }
                    } finally {
                    }
                    tnode10.addChild(myAggregationLinks[1], tnode13);
                    // TODO validate child 
                  }
                } finally {
                }
                tnode9.addChild(myAggregationLinks[8], tnode10);
                // TODO validate child 
              }
              {
                final SNode tnode53 = environment.createOutputNode(myConcepts[18]);
                try {
                  TemplateContext context27 = context6.subContext();
                  {
                    final SNode tnode54 = environment.createOutputNode(myConcepts[13]);
                    try {
                      tnode54.setReference(myAssociationLinks[1], SReference.create(myAssociationLinks[1], tnode54, PersistenceFacade.getInstance().createModelReference("r:f5e9b11f-5073-4786-8ed1-a9e42307c3f8(JavaKaja.runtime)"), PersistenceFacade.getInstance().createNodeId("3210697320273648281")));
                      TemplateContext context28 = context27.subContext();
                      {
                        final SNode tnode55 = environment.createOutputNode(myConcepts[10]);
                        try {
                          SNodeAccessUtil.setProperty(tnode55, myProperties[2], TemplateUtil.asString(QueriesGenerated.propertyMacro_GetPropertyValue_6504511466437696085(new PropertyMacroContext(context28, "0", propertyMacro_yon54s_c0a0c0a0b0c0b0b0b0c0b0e0b0b0c0e))));
                        } finally {
                        }
                        tnode54.addChild(myAggregationLinks[3], tnode55);
                        // TODO validate child 
                      }
                    } finally {
                    }
                    tnode53.addChild(myAggregationLinks[14], tnode54);
                    // TODO validate child 
                  }
                  {
                    final SNode tnode56 = environment.createOutputNode(myConcepts[18]);
                    try {
                      TemplateContext context29 = context27.subContext();
                      {
                        final SNode tnode57 = environment.createOutputNode(myConcepts[18]);
                        try {
                          TemplateContext context30 = context29.subContext();
                          {
                            final SNode tnode58 = environment.createOutputNode(myConcepts[13]);
                            try {
                              tnode58.setReference(myAssociationLinks[1], SReference.create(myAssociationLinks[1], tnode58, PersistenceFacade.getInstance().createModelReference("r:f5e9b11f-5073-4786-8ed1-a9e42307c3f8(JavaKaja.runtime)"), PersistenceFacade.getInstance().createNodeId("3210697320273648203")));
                              TemplateContext context31 = context30.subContext();
                              {
                                final SNode tnode59 = environment.createOutputNode(myConcepts[10]);
                                try {
                                  SNodeAccessUtil.setProperty(tnode59, myProperties[2], TemplateUtil.asString(QueriesGenerated.propertyMacro_GetPropertyValue_6504511466437675629(new PropertyMacroContext(context31, "0", propertyMacro_yon54s_c0a0c0a0b0c0b0b0b0b0b0c0b0c0b0e0b0b0c0e))));
                                } finally {
                                }
                                tnode58.addChild(myAggregationLinks[3], tnode59);
                                // TODO validate child 
                              }
                            } finally {
                            }
                            tnode57.addChild(myAggregationLinks[15], tnode58);
                            // TODO validate child 
                          }
                          {
                            final SNode tnode60 = environment.createOutputNode(myConcepts[13]);
                            try {
                              tnode60.setReference(myAssociationLinks[1], SReference.create(myAssociationLinks[1], tnode60, PersistenceFacade.getInstance().createModelReference("r:f5e9b11f-5073-4786-8ed1-a9e42307c3f8(JavaKaja.runtime)"), PersistenceFacade.getInstance().createNodeId("3210697320273648281")));
                              TemplateContext context32 = context30.subContext();
                              {
                                final SNode tnode61 = environment.createOutputNode(myConcepts[10]);
                                try {
                                  SNodeAccessUtil.setProperty(tnode61, myProperties[2], TemplateUtil.asString(QueriesGenerated.propertyMacro_GetPropertyValue_6504511466437682523(new PropertyMacroContext(context32, "0", propertyMacro_yon54s_c0a0c0a0b0c0b0c0b0b0b0c0b0c0b0e0b0b0c0e))));
                                } finally {
                                }
                                tnode60.addChild(myAggregationLinks[3], tnode61);
                                // TODO validate child 
                              }
                            } finally {
                            }
                            tnode57.addChild(myAggregationLinks[14], tnode60);
                            // TODO validate child 
                          }
                        } finally {
                        }
                        tnode56.addChild(myAggregationLinks[15], tnode57);
                        // TODO validate child 
                      }
                      {
                        final SNode tnode62 = environment.createOutputNode(myConcepts[13]);
                        try {
                          tnode62.setReference(myAssociationLinks[1], SReference.create(myAssociationLinks[1], tnode62, PersistenceFacade.getInstance().createModelReference("r:f5e9b11f-5073-4786-8ed1-a9e42307c3f8(JavaKaja.runtime)"), PersistenceFacade.getInstance().createNodeId("3210697320273648203")));
                          TemplateContext context33 = context29.subContext();
                          {
                            final SNode tnode63 = environment.createOutputNode(myConcepts[10]);
                            try {
                              SNodeAccessUtil.setProperty(tnode63, myProperties[2], TemplateUtil.asString(QueriesGenerated.propertyMacro_GetPropertyValue_6504511466437689050(new PropertyMacroContext(context33, "1", propertyMacro_yon54s_c0a0c0a0b0c0b0c0b0c0b0c0b0e0b0b0c0e))));
                            } finally {
                            }
                            tnode62.addChild(myAggregationLinks[3], tnode63);
                            // TODO validate child 
                          }
                        } finally {
                        }
                        tnode56.addChild(myAggregationLinks[14], tnode62);
                        // TODO validate child 
                      }
                    } finally {
                    }
                    tnode53.addChild(myAggregationLinks[15], tnode56);
                    // TODO validate child 
                  }
                } finally {
                }
                tnode9.addChild(myAggregationLinks[13], tnode53);
                // TODO validate child 
              }
            } finally {
            }
            tnode2.addChild(myAggregationLinks[1], tnode9);
            // TODO validate child 
          }
        } finally {
        }
        tnode1.addChild(myAggregationLinks[16], tnode2);
        // TODO validate child 
      }
    } finally {
    }
    return tnode1;
  }
  @Override
  public Collection<SNode> apply(@NotNull TemplateExecutionEnvironment environment, @NotNull TemplateContext context) throws GenerationException {
    return TemplateUtil.singletonList(applyPart0(context));
  }

  @Override
  public Collection<SNode> weave(@NotNull NodeWeaveFacility.WeaveContext weaveContext, @NotNull NodeWeaveFacility weaveSupport) throws GenerationException {
    final TemplateContext templateContext = weaveSupport.getTemplateContext();
    SNode tnodepart0 = applyPart0(templateContext);
    weaveSupport.weaveNode(MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"), tnodepart0);
    return TemplateUtil.singletonList(tnodepart0);
  }
  @Override
  protected SConcept[] initConcepts() {
    SConcept[] rv = new SConcept[19];
    rv[0] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0xfc092b6b77L, "BlockStatement");
    rv[1] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0xf8cc56b200L, "StatementList");
    rv[2] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0x57d533a7af15ed3aL, "SingleLineComment");
    rv[3] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0x57d533a7af15ed3dL, "TextCommentPart");
    rv[4] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0xf8cc56b217L, "IfStatement");
    rv[5] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0xf8cc67c7f0L, "LocalVariableDeclarationStatement");
    rv[6] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0xf8cc67c7efL, "LocalVariableDeclaration");
    rv[7] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0x101de48bf9eL, "ClassifierType");
    rv[8] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0x10ab8473cc5L, "GenericNewExpression");
    rv[9] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0x11a59b0fbceL, "ClassCreator");
    rv[10] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0xf8cc59b314L, "IntegerConstant");
    rv[11] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0xf8cc56b215L, "Statement");
    rv[12] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0xf8cc56b213L, "ExpressionStatement");
    rv[13] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0x6c6b6a1e379f9404L, "LocalMethodCall");
    rv[14] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0xf8c77f1e98L, "VariableReference");
    rv[15] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0x116b46a08c4L, "DotExpression");
    rv[16] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0x11126b40c25L, "ArrayAccessExpression");
    rv[17] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0x118154a6332L, "InstanceMethodCallOperation");
    rv[18] = MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage"), 0xfb7c3070eeL, "AndExpression");
    return rv;
  }
  @Override
  protected SProperty[] initProperties() {
    SProperty[] rv = new SProperty[3];
    rv[0] = MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x57d533a7af15ed3dL, 0x57d533a7af15ed3eL, "text");
    rv[1] = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    rv[2] = MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc59b314L, 0xf8cc59b315L, "value");
    return rv;
  }
  @Override
  protected SReferenceLink[] initAssociationLinks() {
    SReferenceLink[] rv = new SReferenceLink[3];
    rv[0] = MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x101de48bf9eL, 0x101de490babL, "classifier");
    rv[1] = MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301adL, "baseMethodDeclaration");
    rv[2] = MetaAdapterFactory.getReferenceLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c77f1e98L, 0xf8cc6bf960L, "variableDeclaration");
    return rv;
  }
  @Override
  protected SContainmentLink[] initAggregationLinks() {
    SContainmentLink[] rv = new SContainmentLink[17];
    rv[0] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x57d533a7af15ed3aL, 0x57d533a7af16ff73L, "commentPart");
    rv[1] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement");
    rv[2] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x450368d90ce15bc3L, 0x4ed4d318133c80ceL, "type");
    rv[3] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11857355952L, 0xf8c78301aeL, "actualArgument");
    rv[4] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10ab8473cc5L, 0x10ab847b486L, "creator");
    rv[5] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37a7f6eL, 0xf8c37f506eL, "initializer");
    rv[6] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc67c7f0L, 0xf8cc67c7f1L, "localVariableDeclaration");
    rv[7] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b213L, 0xf8cc56b214L, "expression");
    rv[8] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b217L, 0xf8cc56b219L, "ifTrue");
    rv[9] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11126b40c25L, 0x11126b6ac89L, "index");
    rv[10] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x11126b40c25L, 0x11126b6de5aL, "array");
    rv[11] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, 0x116b46a4416L, "operand");
    rv[12] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x116b46a08c4L, 0x116b46b36c4L, "operation");
    rv[13] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b217L, 0xf8cc56b218L, "condition");
    rv[14] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfbdeb6fecfL, 0xfbdeb7a11bL, "rightExpression");
    rv[15] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfbdeb6fecfL, 0xfbdeb7a11cL, "leftExpression");
    rv[16] = MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xfc092b6b77L, 0xfc092b6b78L, "statements");
    return rv;
  }
  private static SNodePointer propertyMacro_yon54s_c0a0c0a0b0c0b0b0b0c0b0b0b0e0b0b0b0c0b0b0b0c0b0b0b0e0b0b0c0e = new SNodePointer("r:262b93f0-fe86-497c-93c5-efd684d05bc6(jetbrains.mps.samples.KajaSceneConstruction.generator.template.main@generator)", "6504511466437722202");
  private static SNodePointer propertyMacro_yon54s_c0a0c0a0b0d0b0b0b0c0b0b0b0e0b0b0b0c0b0b0b0c0b0b0b0e0b0b0c0e = new SNodePointer("r:262b93f0-fe86-497c-93c5-efd684d05bc6(jetbrains.mps.samples.KajaSceneConstruction.generator.template.main@generator)", "6504511466437729263");
  private static SNodePointer propertyMacro_yon54s_c0a0c0a0b0c0b0b0b0d0b0b0b0e0b0b0b0c0b0b0b0c0b0b0b0e0b0b0c0e = new SNodePointer("r:262b93f0-fe86-497c-93c5-efd684d05bc6(jetbrains.mps.samples.KajaSceneConstruction.generator.template.main@generator)", "6504511466437736825");
  private static SNodePointer propertyMacro_yon54s_c0a0c0a0b0d0b0b0b0d0b0b0b0e0b0b0b0c0b0b0b0c0b0b0b0e0b0b0c0e = new SNodePointer("r:262b93f0-fe86-497c-93c5-efd684d05bc6(jetbrains.mps.samples.KajaSceneConstruction.generator.template.main@generator)", "6504511466437743196");
  private static SNodePointer copySrcMacro_yon54s_b0a0c0e0b0b0b0e0b0b0b0c0b0b0b0c0b0b0b0e0b0b0c0e = new SNodePointer("r:262b93f0-fe86-497c-93c5-efd684d05bc6(jetbrains.mps.samples.KajaSceneConstruction.generator.template.main@generator)", "2286872346382915220");
  private static SNodePointer templateSwitchNodeNoInput_yon54s_a0a0c0b0f0b0b0b0e0b0b0b0c0b0b0b0c0b0b0b0e0b0b0c0e = new SNodePointer("r:262b93f0-fe86-497c-93c5-efd684d05bc6(jetbrains.mps.samples.KajaSceneConstruction.generator.template.main@generator)", "2000624636391164068");
  private static SNodePointer copySrcListMacro_yon54s_b0a0a1a3a1a5a1a1a1a4a1a1a1a2a1a1a1a2a1a1a1a4a1a1a2a4 = new SNodePointer("r:262b93f0-fe86-497c-93c5-efd684d05bc6(jetbrains.mps.samples.KajaSceneConstruction.generator.template.main@generator)", "6504511466447542748");
  private static SNodePointer propertyMacro_yon54s_c0a0c0a0b0c0b0b0b0e0b0b0b0c0b0b0b0e0b0b0c0e = new SNodePointer("r:262b93f0-fe86-497c-93c5-efd684d05bc6(jetbrains.mps.samples.KajaSceneConstruction.generator.template.main@generator)", "6504511466439200433");
  private static SNodePointer propertyMacro_yon54s_c0a0c0a0b0d0b0b0b0e0b0b0b0c0b0b0b0e0b0b0c0e = new SNodePointer("r:262b93f0-fe86-497c-93c5-efd684d05bc6(jetbrains.mps.samples.KajaSceneConstruction.generator.template.main@generator)", "6504511466439208104");
  private static SNodePointer templateNode_yon54s_c0a0a1a4a1a1a1a4a1a1a1a2a1a1a1a4a1a1a2a4 = new SNodePointer("r:262b93f0-fe86-497c-93c5-efd684d05bc6(jetbrains.mps.samples.KajaSceneConstruction.generator.template.main@generator)", "6504511466438379801");
  private static SNodePointer propertyMacro_yon54s_c0a0c0a0b0b0b0b0b0c0b0c0b0b0b0e0b0b0c0e = new SNodePointer("r:262b93f0-fe86-497c-93c5-efd684d05bc6(jetbrains.mps.samples.KajaSceneConstruction.generator.template.main@generator)", "6504511466437709892");
  private static SNodePointer propertyMacro_yon54s_c0a0c0a0b0b0b0c0b0b0b0c0b0c0b0b0b0e0b0b0c0e = new SNodePointer("r:262b93f0-fe86-497c-93c5-efd684d05bc6(jetbrains.mps.samples.KajaSceneConstruction.generator.template.main@generator)", "6504511466437702717");
  private static SNodePointer copySrcMacro_yon54s_b0a0c0c0b0c0b0c0b0c0b0b0b0e0b0b0c0e = new SNodePointer("r:262b93f0-fe86-497c-93c5-efd684d05bc6(jetbrains.mps.samples.KajaSceneConstruction.generator.template.main@generator)", "2286872346383052769");
  private static SNodePointer propertyMacro_yon54s_c0a0c0a0b0c0b0b0b0c0b0e0b0b0c0e = new SNodePointer("r:262b93f0-fe86-497c-93c5-efd684d05bc6(jetbrains.mps.samples.KajaSceneConstruction.generator.template.main@generator)", "6504511466437696084");
  private static SNodePointer propertyMacro_yon54s_c0a0c0a0b0c0b0b0b0b0b0c0b0c0b0e0b0b0c0e = new SNodePointer("r:262b93f0-fe86-497c-93c5-efd684d05bc6(jetbrains.mps.samples.KajaSceneConstruction.generator.template.main@generator)", "6504511466437675628");
  private static SNodePointer propertyMacro_yon54s_c0a0c0a0b0c0b0c0b0b0b0c0b0c0b0e0b0b0c0e = new SNodePointer("r:262b93f0-fe86-497c-93c5-efd684d05bc6(jetbrains.mps.samples.KajaSceneConstruction.generator.template.main@generator)", "6504511466437682522");
  private static SNodePointer propertyMacro_yon54s_c0a0c0a0b0c0b0c0b0c0b0c0b0e0b0b0c0e = new SNodePointer("r:262b93f0-fe86-497c-93c5-efd684d05bc6(jetbrains.mps.samples.KajaSceneConstruction.generator.template.main@generator)", "6504511466437689049");
}
