package jetbrains.mps.samples.Kaja.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.IconResource;

public class IconContainer {
  protected static IconResource RESOURCE_a0a2a0a31b0fb = new IconResource("TextIcon_928359275.png", IconContainer.class);
  protected static IconResource RESOURCE_a0a2a0a42b0fb = new IconResource("TextIcon_1.png", IconContainer.class);
}
