package jetbrains.mps.samples.Kaja.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.runtime.TemplateMappingScript;
import org.jetbrains.mps.openapi.model.SNodeReference;
import org.jetbrains.mps.openapi.model.SModel;
import jetbrains.mps.generator.template.ITemplateGenerator;
import jetbrains.mps.generator.template.MappingScriptContext;
import jetbrains.mps.smodel.SNodePointer;

@Generated
public class Script_RemoveEmptyLines implements TemplateMappingScript {
  public Script_RemoveEmptyLines() {
  }
  public SNodeReference getScriptNode() {
    return mappingScriptNode;
  }
  public String getLongName() {
    return "'RemoveEmptyLines' (jetbrains.mps.samples.Kaja.generator.template.main@generator)";
  }
  public boolean modifiesModel() {
    return true;
  }
  public int getKind() {
    return PREPROCESS;
  }
  public void apply(SModel model, ITemplateGenerator generator) {
    QueriesGenerated.mappingScript_CodeBlock_3308300503039761163(new MappingScriptContext(model, getScriptNode(), generator));
  }
  private static SNodePointer mappingScriptNode = new SNodePointer("r:3ab3501c-2f4b-48e6-9b6c-e31ff8ef3185(jetbrains.mps.samples.Kaja.generator.template.main@generator)", "3308300503039761162");
}
