package JavaKaja.runtime;

/*Generated by MPS */

import java.util.List;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;

public abstract class Cell {
  protected Vehicle vehicle = null;
  protected List<Direction> directions;
  private static final Color DEFAULT_COLOUR = Color.WHITE;

  public Cell(Direction... direction) {
    this.directions = new ArrayList<Direction>(Arrays.asList(direction));
  }

  public abstract void setVehicle(Vehicle vehicle);

  public void unsetVehicle() {
    this.vehicle = null;
  }

  public boolean hasVehicle() {
    return vehicle != null;
  }

  public Vehicle getVehicle() {
    return vehicle;
  }

  public abstract void addDirection(Direction direction);

  public void tickVehicle() {
    if (hasVehicle()) {
    }
    return;
  }

  public Color getColor() {
    return DEFAULT_COLOUR;
  }

  public abstract boolean isDrivable(Direction direction);

  public boolean hasDirection(Direction direction) {
    for (Direction existingDirection : this.directions) {
      if (existingDirection == direction) {
        return true;
      }
    }
    return false;
  }
}
