package JavaKaja.runtime;

/*Generated by MPS */

import javax.swing.JPanel;
import javax.swing.JLabel;
import java.awt.BorderLayout;
import javax.swing.border.LineBorder;
import javax.swing.Icon;

public class VisualCell extends JPanel {
  private JLabel canvas = new JLabel();
  public VisualCell() {
    setLayout(new BorderLayout());
    canvas.setVerticalTextPosition(JLabel.BOTTOM);
    canvas.setHorizontalAlignment(JLabel.CENTER);
    add(canvas, BorderLayout.CENTER);
    setBorder(LineBorder.createGrayLineBorder());
  }
  public void setIcon(Icon icon) {
    canvas.setIcon(icon);
  }
  public void setMarks(String marks) {
    canvas.setText(marks);
  }
}
